config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :posts
  devise_for :users

  resources :users

  root to: "posts#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments, through: :posts


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def respond_modal_with(*args, &blk)
    options = args.extract_options!
    options[:responder] = ModalResponder
    respond_with *args, options, &blk
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new

    @comment.post_id == params[:post_id]
    @comment.user_id == params[:user_id]
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment: comment_params[:comment], post_id: params[:post_id], user_id: params[:user_id])


      @comment.post_id == params[:post_id]
      @comment.user_id == params[:user_id]

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(params[:post_id]), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:comment, :user_id, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.paginate(:page => params[:page], :per_page => 5).order(created_at: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    @post.update(user_id: current_user.id)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:post, :title)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    @user.first_name = user_params[:first_name]
    @user.last_name = user_paras[:last_name]

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :password, :password_confirmation, :user_id, :post_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for @comment, :url => comments_path(post_id: params[:post_id], user_id: params[:user_id]), html: { data: { :method => :post }} do |f| %>
    <% if @comment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

          <ul>
            <% @comment.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :comment %><br>
      <%= f.text_area :comment, class:"form-control"%>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>
<div class=row>
  <div class="col-md-8 col-md-offset-2">

<h1>Listing Comments</h1>

<table class="table">
  <thead>
    <tr>
      <th>Comment</th>
      <th>User</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.comment %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.post_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path, class:"btn btn-default"%>
</div>
  </div>

app/views/comments/new.html.erb
<div class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2>Modal Test?</h2>
      </div>
      <%= render 'form' %>

      <%= link_to 'Back', comments_path %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>
<div class=row>
  <div class="col-md-8 col-md-offset-2">
<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment), class:"btn btn-default" %>
<%= link_to 'Comments', comments_path, class:"btn btn-default" %>
</div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails Review</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div class = row>
  <div class="col-md-10 col-md-offset-1">
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <%= link_to "Rails Review Page", root_path, class: "navbar-brand logo-text" %>
        <% if !current_user %>
            <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-default navbar-btn", id:"sign-up-btn"%>
        <% end %>
        <% if current_user %>
            <%= link_to "Sign Out", destroy_user_session_path, :method=>'delete', class: "btn btn-danger navbar-btn pull-right", id:"sign-out-btn" %>
        <% else %>
            <%= link_to "Sign In", "#logInModal", "data-toggle" => "modal", class:"btn btn-primary", id:"sign-in-btn" %>
        <% end %>
      </div>
    </nav>
  </div>
</div>

<%= yield %>

<%= render "shared/login_modal" %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="text">
      <%= f.label :title %><br>
      <%= f.text_field :title, class:"form-control" %>
    </div>

  <div class="field">
    <%= f.label :post %><br>
    <%= f.text_area :post, class:"form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-default" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<div class=row>
  <div class="col-md-8 col-md-offset-2">
    <h1>The Stuntz Rails Review Message Board</h1>

    <table class="table">
      <thead>
      <tr>
        <th>Post</th>
        <th>Author</th>
        <th colspan="3"></th>
        <th>Comments</th>
      </tr>
      </thead>

      <tbody>
      <% if current_user %>
          <% @posts.each do |post| %>
              <tr>
                <td><%= post.title %></td>
                <td><%= post.user.first_name %> </td>
                <td><%= link_to 'Show', post, class: 'btn btn-default' %></td>
                <% if post.user_id == current_user.id %>
                    <td><%= link_to 'Edit', edit_post_path(post), class: 'btn btn-default' %></td>
                    <td><%= link_to 'Destroy', post, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %></td>
                <% else %>
                    <td></td>
                    <td></td>
                <% end %>

                <td> <%= post.comments.length %>  </td>

              </tr>
          <% end %>
      <% end %>
      </tbody>
    </table>

    <br>
    <%= will_paginate @posts %>
    <% if current_user %>
        <%= link_to 'New Post', new_post_path, class:"btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class=row>
  <div class="col-md-8 col-md-offset-2" id="new-post-form">
    <h1>New Post</h1>
<%= render 'form' %>

<%= link_to 'Back', posts_path %>
</div>
  </div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= render "shared/comment_form" %>

<div class=row>
  <div class="col-md-8 col-md-offset-2">
    <p>
      <strong>Post: <%= @post.title %></strong>
      <h1><%= @post.post %></h1>
    </p>
    <div class="row">
      <div class="col-md-6">
        <h3>Created by <%=@post.user.first_name%> </h3>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <h4>Comments:</h4>
      </div>
    </div>
    <table class="table">
      <thead>
      <tr>
        <th>User</th>
        <th> Comment</th>
        <th> Date </th>
      </tr>
      </thead>
      <tbody>
      <% @comments = @post.comments %>
      <% @comments = @comments.paginate(:page => params[:page], :per_page => 5).order(created_at: :asc).each do |comment| %>
          <tr>
            <td><%= comment.user.first_name.capitalize %> <%= comment.user.last_name.capitalize %></td>
            <td><%= comment.comment%> </td>
            <td><%= comment.created_at.to_formatted_s(:long)%> </td>
            <td><%= link_to "Remove Comment", comment, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %></td>
          </tr>
          </tbody>
      <% end %>
      </table>

      <%= link_to "Comment", "#myModal", "data-toggle" => "modal", class:"btn btn-primary" %>

      <%= link_to 'Edit', edit_post_path(@post), class:"btn btn-default" %>
      <%= link_to 'Posts', posts_path, class:"btn btn-default" %>
      <%= will_paginate @comments %>
  </div>
</div>

app/views/shared/_comment_form.html.erb
<div class="modal" id="myModal">
  <div class="modal-dialog" role="document" id="myModal">
    <div class="modal-content">
      <div class="modal-header">
        <h2>Comment on the post</h2>
      </div>
      <div class="modal-body" id="commentModalBody">

        <% @comment = Comment.new %>
        <%= form_for @comment, :url => comments_path(post_id: @post.id, user_id: current_user.id), html: { :method => :post } do |f| %>
            <% if @comment.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

                  <ul>
                    <% @comment.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>

            <div class="field">
              <%= f.label :comment %><br>
              <%= f.text_area :comment, class:"form-control"%>
            </div>

            <div class="actions">
              <%= f.submit class:"btn btn-default" %>
            </div>
        <% end %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>

app/views/shared/_login_modal.html.erb
<div class="modal" id="logInModal">
  <div class="modal-dialog" role="document" id="myModal">
    <div class="modal-content">
      <div class="modal-header">
       <h2>Log in</h2>
      </div>
      <div class="modal-body">
        <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
            <div class="field">
              <%= f.label :email%><br />
              <%= f.email_field :email, autofocus: true, class: "form-control" %>
            </div>

            <div class="field">
              <%= f.label :password %><br />
              <%= f.password_field :password, autocomplete: "off", class:"form-control" %>
            </div>

            <% if devise_mapping.rememberable? -%>
                <div class="field">
                  <%= f.check_box :remember_me %>
                  <%= f.label :remember_me %>
                </div>
            <% end -%>

            <div class="actions">
              <%= f.submit "Log in", class: "btn btn-default"%>
            </div>
        <% end %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

    <% f.input :first_name, class="form-control" %>
    <% f.input :last_name, class="form-control" %>
    <% f.input :email, class="form-control" %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div class = row>
  <div class="col-md-10 col-md-offset-1">
<h1>Listing Users</h1>
  <table class="table table-condensed">
    <thead>
    <tr>
      <th>Email</th>
      <th>Registered</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.email, user %></td>
          <td><%= user.created_at.to_date %></td>
          <td><%= link_to "Edit", edit_user_path(user), :class => 'btn btn-mini' %></td>
          <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
    <%= link_to 'New User', new_user_session_path, class: "btn btn-default"%>
</div>

<br>


</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<div class = row>
  <div class="col-md-10 col-md-offset-1">
    <h3>Users</h3>
  <table class="table table-condensed">
    <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Registered</th>
      <th>Role</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.name, user %></td>
          <td><%= user.email %></td>
          <td><%= user.created_at.to_date %></td>
          <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
          <td>
            <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
            <%= render user %>
          </td>
          <td><%= link_to "Edit", edit_user_path(user), :class => 'btn btn-mini' %></td>
          <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <div class="pagination-wrapper">
    <%= page_navigation_links @users if @users.present? %>
  </div>
    </div>
  </div>